"""Add is_autogenerated column to posts

Revision ID: fc2d2bc269b9
Revises: 41108a12eaa4
Create Date: 2024-08-13 18:01:53.980916

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc2d2bc269b9"
down_revision: Union[str, None] = "41108a12eaa4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "is_autogenerated",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.execute(
        "UPDATE posts SET is_autogenerated = true WHERE CAST(owner_id AS INTEGER) < 6"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "is_autogenerated")
    # ### end Alembic commands ###
