import os

SQLALCHEMY_DATABASE_URL = os.getenv("SQLALCHEMY_DATABASE_URL_DOCKER")
MONGODB_URL = os.getenv("MONGODB_URL_DOCKER")
SECRET_KEY = os.getenv("SECRET_KEY")
CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRET = os.getenv("CLIENT_SECRET")
DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")

